package abstractfactory;

import abstractfactory.db.DBServiceStackFactory;
import abstractfactory.impl.IServiceStackAbstractFactory;
import abstractfactory.rest.RestServiceStackFactory;
import abstractfactory.schemas.Employee;
import abstractfactory.schemas.Product;
import abstractfactory.ws.WSServiceStackFactory;

import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Client extends javax.swing.JFrame {

    HashMap<String, IServiceStackAbstractFactory> factories;

    public Client() {
        factories = new HashMap<>(
                Map.of(
                        "db", new DBServiceStackFactory(),
                        "ws", new WSServiceStackFactory(),
                        "rest", new RestServiceStackFactory()
                )
        );

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLblEmployees = new javax.swing.JLabel();
        jLblProducts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblEmployees = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblProducts = new javax.swing.JTable();
        jLblTipoServicioEmployees = new javax.swing.JLabel();
        jLblTipoServicioProducts = new javax.swing.JLabel();
        jCbxProducts = new javax.swing.JComboBox<>();
        jCbxEmployees = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblEmployees.setText("EMPLEADOS");

        jLblProducts.setText("PRODUCTOS");

        jTblEmployees.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "NOMBRE"
                }
        ));
        jScrollPane2.setViewportView(jTblEmployees);

        jTblProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "NOMBRE"
                }
        ));
        jScrollPane3.setViewportView(jTblProducts);

        jLblTipoServicioEmployees.setText("Tipo de Servicio");

        jLblTipoServicioProducts.setText("Tipo de Servicio");

        jCbxProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"db", "rest", "ws"}));
        jCbxProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxProductsActionPerformed(evt);
            }
        });

        jCbxEmployees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"db", "rest", "ws"}));
        jCbxEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLblProducts)
                                                .addGap(397, 397, 397))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLblTipoServicioProducts)
                                                                                .addGap(0, 55, Short.MAX_VALUE))
                                                                        .addComponent(jCbxProducts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLblTipoServicioEmployees)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(jCbxEmployees, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(189, 189, 189))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLblEmployees)
                                                .addGap(398, 398, 398))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLblEmployees)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLblTipoServicioEmployees)
                                                .addGap(28, 28, 28)
                                                .addComponent(jCbxEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(203, 203, 203)
                                .addComponent(jLblProducts)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblTipoServicioProducts)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCbxProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jCbxProductsActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener el valor seleccionado
        String tipoServicio = (String) jCbxProducts.getSelectedItem();
        System.out.println(tipoServicio);
        IServiceStackAbstractFactory factory = factories.get(tipoServicio);
        if (factory != null) {
            List<Product> products = factory.createProductsService().getProducts();
            llenarTablaProducts(products);
        }
    }

    private void llenarTablaProducts(List<Product> products) {
        limpiarTablaProducts();
        DefaultTableModel model = (DefaultTableModel) jTblProducts.getModel();
        for (Product product : products) {
            model.addRow(new Object[]{product.getId(), product.getName()});
        }
    }

    private void limpiarTablaProducts() {
        DefaultTableModel model = (DefaultTableModel) jTblProducts.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private void jCbxEmployeesActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener el valor seleccionado
        String tipoServicio = (String) jCbxEmployees.getSelectedItem();
        System.out.println(tipoServicio);
        IServiceStackAbstractFactory factory = factories.get(tipoServicio);
        if (factory != null) {
            List<Employee> employees = factory.createEmployeeService().getEmployees();
            llenarTablaEmployees(employees);
        }
    }

    private void llenarTablaEmployees(List<Employee> employees) {
        limpiarTablaEmployees();
        DefaultTableModel model = (DefaultTableModel) jTblEmployees.getModel();
        for (Employee employee : employees) {
            model.addRow(new Object[]{employee.getId(), employee.getName()});
        }
    }

    private void limpiarTablaEmployees() {
        DefaultTableModel model = (DefaultTableModel) jTblEmployees.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> jCbxEmployees;
    private javax.swing.JComboBox<String> jCbxProducts;
    private javax.swing.JLabel jLblEmployees;
    private javax.swing.JLabel jLblProducts;
    private javax.swing.JLabel jLblTipoServicioEmployees;
    private javax.swing.JLabel jLblTipoServicioProducts;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblEmployees;
    private javax.swing.JTable jTblProducts;
    // End of variables declaration
}
